name: Auto-update casks on new releases

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Fetch latest versions
        run: |-
          curl "https://api.github.com/repos/mtgatool/mtgatool-desktop/releases" | jq '.[0] | .name' > latest
      - name: Update Casks
        run: |-
          sed -i "s/version .*/version $(cat latest)/g" Casks/mtg-arena-tool.rb

          if [[ `git status --porcelain` ]]; then
            echo "New version detected: $(cat latest)"
            rm latest

            git config user.name "Auto Updater"
            git config user.email "actions@users.noreply.github.com"
            git add -A
            timestamp=$(date -u)
            git commit -m "Auto-update Casks: ${timestamp}" || exit 0
            git push
          fi
